# Authentication
CONFIG_SECRET_KEY = ""

# Database
DATABASE_NAME = ""

# Storage
CONFIG_STORAGE_PATH = "" 

# ElasticSearch
ELASTICSEARCH_HOST = ""  
ELASTICSEARCH_PORT = 9200  
ELASTICSEARCH_INDEX_NAME = ""

# Hugging Face
HUGGINGFACE_API_KEY = ""